language: python
python:
  - 3.6

sudo: false

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  
  # Install pandas + some optional dependencies
  - conda install pandas matplotlib seaborn jinja2 ipython sphinx ipykernel jinja2
  - conda install -c conda-forge nbsphinx

  # install doctr
  - conda install -c conda-forge doctr

script:
  - set -e
  - cd pandas-docs
  - python make.py html

